kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: k8
    trainer: siva
  annotations:
    kubernetes.io/created-by: "sivas"
    jenkins.build.url: 'https://jenkins.daws79s.online/expense/job/backend/54'

spec: 
  containers:
  - name: nginx
    image: ngine 