kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers: 
  - name: nginx
    image: nginx
    resources:
  # soft limit
      requests:
       cpu: "100m"
        memory: "128Mi"  
    #limits should be atleat or more then req
       limits:
        cpu: "100m"
        memory: "128Mi"