kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev 
  ports:
  - portcol: TCP
    port: 80 # service port
    targetPort: 80  # target-port


  