apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev 
  ports:
  - portcol: TCP
    port: 8080 # service port
    targetPort: 8080  # target-port


  